name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Image optimization
        uses: actions/cache@v3
        with:
          path: |
            node_modules/.astro
          key: ${{ runner.os }}-astro-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-astro-cache-

      - name: Install, build, and upload your site output
        uses: withastro/action@v2

      - name: Delete old caches
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH="refs/heads/main"

          echo "Fetching list of cache keys..."
          cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting old caches..."
          for cacheKey in $cacheKeys
          do
              if [[ $cacheKey != *"${{ github.run_id }}"* ]]; then
                  gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
              fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
